# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9c17adb4b2e7d15510e9c3fdec44ddc712f5da711da7996058243e67306282d8f1159a2b703133756f77ebd4ec0e6277c4fcafa6ae8cdd3edc427044e1cb85

test:
  secret_key_base: 3b79b0538bb52ceb6304ba66a6e34d879e1f0768266fa65e137f1406243f3489289658b587ef81b8dffd8d378157027bcaf6f7ab2addcb68e17b392b7c269420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
